import json
import time
from fastapi import APIRouter, Header, HTTPException, Depends
from pydantic import BaseModel, Field
from typing import Optional
import sqlite3
from database import get_db

router = APIRouter()


# ── Auth helper ──────────────────────────────────────────────────────────────

def require_api_key(x_api_key: str = Header(..., alias="X-API-Key")) -> str:
    db = get_db()
    row = db.execute(
        "SELECT owner FROM api_keys WHERE key=? AND active=1", (x_api_key,)
    ).fetchone()
    db.close()
    if not row:
        raise HTTPException(401, "Invalid or inactive API key")
    return row["owner"]


# ── Request model ─────────────────────────────────────────────────────────────

class RegisterPayload(BaseModel):
    artifact_id:   str  = Field(..., description="Unique artifact ID from Fade")
    sha256:        str  = Field(..., description="SHA-256 hex of the original export")
    phash:         Optional[str]  = Field(None, description="Perceptual hash hex (video/image)")
    wm_id:         Optional[str]  = Field(None, description="Watermark ID prefix (8 hex chars)")
    merkle_proof:  Optional[list] = Field(None, description="Merkle proof array")
    merkle_root:   Optional[str]  = Field(None, description="Merkle root anchored on ledger")
    ledger_tx:     Optional[str]  = Field(None, description="Blockchain TX hash (if EVM)")
    filename:      Optional[str]  = Field(None, description="Original filename")
    content_type:  Optional[str]  = Field("video", description="video | image | pdf")
    size_bytes:    Optional[int]  = Field(None, description="File size in bytes")


# ── Route ─────────────────────────────────────────────────────────────────────

@router.post("/registerContent", summary="Register a Fade artifact proof bundle")
def register_content(
    payload: RegisterPayload,
    owner: str = Depends(require_api_key),
):
    """
    Called by Fade after a successful integrity registration.
    Stores the proof bundle (hashes only — never the file itself).

    Headers:
        X-API-Key: <your-api-key>

    Body (JSON):
        artifact_id   : string  — unique ID generated by Fade
        sha256        : string  — SHA-256 of the original export
        phash         : string? — perceptual hash (video/image only)
        wm_id         : string? — 8-char hex watermark ID
        merkle_proof  : array?  — Merkle proof path
        merkle_root   : string? — Merkle root (anchored on ledger)
        ledger_tx     : string? — Ethereum TX hash (if blockchain mode)
        filename      : string? — original filename
        content_type  : string? — video | image | pdf  (default: video)
        size_bytes    : int?    — file size in bytes

    Returns:
        { ok: true, artifact_id: "...", registered_at: <unix_ts> }
    """
    db = get_db()
    existing = db.execute(
        "SELECT id FROM artifacts WHERE id=?", (payload.artifact_id,)
    ).fetchone()
    if existing:
        db.close()
        raise HTTPException(409, f"Artifact {payload.artifact_id!r} already registered.")

    now = int(time.time())
    db.execute(
        """INSERT INTO artifacts
           (id, sha256, phash, wm_id, merkle_proof, merkle_root, ledger_tx,
            filename, content_type, size_bytes, registered_at, registered_by)
           VALUES (?,?,?,?,?,?,?,?,?,?,?,?)""",
        (
            payload.artifact_id,
            payload.sha256,
            payload.phash,
            payload.wm_id,
            json.dumps(payload.merkle_proof) if payload.merkle_proof else None,
            payload.merkle_root,
            payload.ledger_tx,
            payload.filename,
            payload.content_type or "video",
            payload.size_bytes,
            now,
            owner,
        ),
    )
    db.commit()
    db.close()
    return {"ok": True, "artifact_id": payload.artifact_id, "registered_at": now}
